name: test_env_xrft
channels:
  - conda-forge
  - defaults
dependencies:
  - codecov
  - xarray
  - dask
  - numpy
  - numpy_groupies
  - scipy
  - pytest
  - pytest-cov
  - pytest-xdist
  - cftime
  - pip
